### ISSUE TITLE
Can't see any Actions while pushing

### ISSUE THREAD

**Issue by jtarrieu** [polomarcus/tp#2]
Bonjour, concernant la partie bonus du tp-functional-programming-scala le fichier scala.yml ne s'exécute pas, ou du moins je n'ai rien de visible dans la section **[Actions](https://github.com/jtarrieu/tp_data_processing/actions/new)**  de github.

Lien de mon repo : [tp_1_processing](https://github.com/jtarrieu/tp_data_processing)

Voici le code du fichier sacala.yml
```yaml
name: Scala CI

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: init and load data
        run: docker-compose -f src/test/docker/docker-compose.yml up -d
      - name: sleep
        run:  sleep 120
      - name: log
        run: docker logs docker_app_1
```

Voici le code du Dockerfile
```Dockerfile
FROM mozilla/sbt:8u292_1.5.7

WORKDIR /app

# Copy the source code into the container
COPY . .

# Compile the code
RUN sbt compile

# Run the tests
CMD ["sbt", "test"]
```

Voici le code du docker-compose.yml
```yaml
version: '2'
services:
  my-scala-app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/tp
      - .cache/:/root/.cache # trick to save coursier (sbt) cache
```

Normalement le fichier scala.yml est exécuté lors d'un push ou d'une merge request. Pour pouvoir l'exécuter j'ai rajouté une ligne vide dans l'un des fichiers de /src/main puis je fais : 

> dans /tp-funtional-prog...
```bash
git add .
git commit -m "blablaba"
git push
```
J'ai la validation en output que le code est bien push, si je vais sur mon repo git les modifications sont bien là.

Mais quand je vais dans **[Actions](https://github.com/jtarrieu/tp_data_processing/actions/new)** il n'y a rien. Le fichier scala.yml n'est pas executé...
___
Avez-vous une idée du pourquoi du comment ?
